print('Hello world!')
print('What is your name?')
my_name = input()
print('It is good to meet youu, ' + my_name)
print('The length of your nae is:')
print(len(my_name))
print('Whoat is your age?')
my_age = input()
print('You will be ' + str(int(my_age) + 1) + ' in a year. ')
